//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteDeConhecimento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atividade
    {
        public int CodAtv { get; set; }
        public string DescAtv { get; set; }
        public int Vagas { get; set; }
        public double Preco { get; set; }
    }
}
