//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteDeConhecimento.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TESTE_DE_CONHECIMENTOEntities1 : DbContext
    {
        public TESTE_DE_CONHECIMENTOEntities1()
            : base("name=TESTE_DE_CONHECIMENTOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atividade> Atividades { get; set; }
        public virtual DbSet<AxParticipanteAtividade> AxParticipanteAtividades { get; set; }
        public virtual DbSet<AxParticipantePacote> AxParticipantePacotes { get; set; }
        public virtual DbSet<Pacote> Pacotes { get; set; }
        public virtual DbSet<Participante> Participantes { get; set; }
    }
}
