//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteDeConhecimento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        public int CodPar { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Telefone { get; set; }
        public string Categoria { get; set; }
    }
}
